### ISSUE TITLE
Blacksmith stops working with a director w/ UAA enabled

### ISSUE THREAD

**Issue by anishp55** [blacksmith-community/blacksmith#13]
When blacksmith is installed in an environment with a director with UAA enabled, blacksmith will stop working because the token UAA token it has expires.

**Comment by jhunt** [comment]
Digging into this issue, it seems to be related to the fact that gogobosh (the library we use for our BOSH client) only refreshes the UAA oauth2 token when a request fails due to a token fetch error.

https://github.com/cloudfoundry-community/gogobosh/blob/master/client.go#L223-L241

We probably need to either regularly emit a request (which I thought regular cleanup was doing), or we need to spin a goroutine to explicitly refresh the UAA token.

Note that this does _not_ effect the built-in BOSH director that the [Blacksmith Genesis Kit](https://github.com/genesis-community/blacksmith-genesis-kit) spins, since it does _not_ use UAA.

**Comment by anishp55** [comment]
I looked at this some more over the weekend.  it appears to me that when UAA is true, an associated timer job is not created to refresh the token.  There are 2 options i think, modify gogobosh to return the full set of tokens to blacksmith or add the correct timer logic into gogobosh.  I'm looking for suggestions on which direction to take.

**Comment by jhunt** [comment]
I would want to look into why regular BOSH cleanup (which accesses the director semi-frequently) isn't triggering.  I am unclear if that is a timing thing, or if the refresh token isn't valid for any longer than the original access token so there is no "window" where a failed request can be re-attempted after refreshing the token.

**Comment by anishp55** [comment]
another option is to add a GetExpiry() function and then if auth == uaa we can get the Expiry and use that to setup the timer to go a GetToken i think.

**Comment by anishp55** [comment]
@jhunt i think this might have to do with the authentication of basic vs uaa flows.  i've created a very minimal client that i have pointed at both directors and running to get a better idea of where, when, and why its falling over in UAA mode.  it really does look like its token related, and the gogobosh client doesn't seem to have anything to hand refreshing the uaa token.

**Comment by anishp55** [comment]
pr in place.

**Comment by jhunt** [comment]
Should be fixed by #14
